spring:
  application:
    name: category
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/category
    username: postgres
    password: dbmaster
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka
#  instance:
#    hostname: localhost