server:
  port: 8081
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defautZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: discovery